seed: 0

gpu: 'cuda:0'

model:
  custom: true
  arch: 'ResNet18'
  kwargs: {'num_classes': 100}
  tvision:
    name: 'resnet18'
    args: {}

data:
  flag: '100'
  dir: './cifar-data'
  batch_size: 128


train:
  epochs: 200
  lr: 0.1
  lr_scheduler: 'multistep'
  step: 100
  milestones: [40000, 60000]
  gamma: 0.1
  lr_min: 0.
  lr_max: 0.2
  weight_decay: 0.00005
  momentum: 0.9
  batch_replay: 8

test: 40

resume:
  path: './models/ADV_WARM_ResNet-Free-Warm-100-1.4_200.pth'

pgd:
  epsilon: 8.
  alpha: 2.
  iter: 20
  restarts: 10
  delta-init: 'random'

opt:
  level: 'O2'
  loss_scale: 1.0
  store: true

logger:
  wandb: false
  project: 'ADV_WARM'
  run: 'ResNet-Free-100'

save:
  epochs: 40 # the saving time is decreased because batch_replay
  # is equal to 8 and we devide epochs*batch_replay/save
