seed: 0

gpu: 'cuda:1'

model:
  custom: true
  arch: 'ResNet18'
  tvision:
    name: 'resnet18'
    args: {}

data:
  flag: '10'
  dir: './cifar-data'
  batch_size: 32


train:
  epochs: 300
  lr: 0.1
  lr_scheduler: 'cyclic'
  step: 100
  milestones: [100, 125]
  gamma: 0.1
  lr_min: 0.
  lr_max: 0.2
  weight_decay: 0.00005
  momentum: 0.9

mixed:
  adv_epochs: 50

resume:
  path: './models/ADV_WARM_ResNet-Madry_199.pth'

pgd:
  epsilon: 8.
  alpha: 2.
  iter: 40
  restarts: 10
  delta-init: 'random'

opt:
  level: 'O2'
  loss_scale: 1.0
  store: true

logger:
  wandb: false
  project: 'EXP'
  run: 'MIXED_RESNET18'

save:
  epochs: 50