seed: 0

gpu: 'cuda:0'

model:
  custom: true
  arch: 'PreActResNet18'
  tvision:
    name: 'resnet18'
    args: {}

data:
  flag: '10'
  dir: './cifar-data'
  batch_size: 256


train:
  epochs: 200
  lr: 0.1
  lr_scheduler: 'multistep'
  step: 100
  milestones: [40000, 60000]
  gamma: 0.1
  lr_min: 0.
  lr_max: 0.2
  weight_decay: 0.00005
  momentum: 0.9

opt:
  level: 'O2'
  loss_scale: 1.0
  store: true

logger:
  wandb: true
  project: 'CIFAR10N'
  run: 'PREACTRSNET18B256-150e'

save:
  epochs: 50