seed: 0

gpu: 'cuda:1'

model:
    custom: false
    tvision:
        name: 'resnet18'
        args: {}

data:
    flag: '10'
    dir: './cifar-data'
    batch_size: 128


train:
    epochs: 300
    lr: 0.1
    lr_scheduler: 'multistep'
    milestones: [150, 250]
    gamma: 0.1
    lr_min: 0.
    lr_max: 0.2
    step: 100
    weight_decay: 0.00005
    momentum: 0.9
    batch_replay: 8

mixed:
  every_n: false
  n: 2
  adv_epochs: 2

pgd:
    epsilon: 8.
    alpha: 2.
    iter: 8
    restarts: 1
    delta-init: 'random'

opt:
    level: 'O2'
    loss_scale: 1.0
    store: true

logger:
    wandb: true
    project: 'EXP'
    run: 'CIFARMIXED-CYCLIC'

save:
    epochs: 50
